### ISSUE TITLE
Make openssl an RPM dependency

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#2518]
**Problem:**

The openstack module has the `cryptography` and the `pyopenssl` dependency in its requirements.txt file. The latest version of these packages requires openssl version > 1.0.2. The epel repository offers an openssl version that matches this requirement.

**Tasks:**

- [x] Add the openssl version constraint as a dependency to of the RPM
- [x] Verify that the openstack module works correctly with the latest version of the `cryptography` and the `pyopenssl` package set in the requirements.txt file while running against an orchestrator installed using the new RPM. 
- [x] Create a ticket to resume the version bumps of the  `cryptography` and the `pyopenssl` package on the openstack module and on core.
