### ISSUE TITLE
Update openapi-spec-validator dependency to 0.3.x

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#2729]
**Problem:**

Version 0.3.0 of the `openapi-spec-validator` dependency introduces a breaking change in the openapi json schema. For example, the fields on the Response object have changed (See: https://github.com/p1c2u/openapi-spec-validator/pull/110). This ticket should make sure that inmanta-core works correctly with the latest version of `openapi-spec-validator`.

**Tasks:**
- [x] Bump the version of the `openapi-spec-validator` to the latest version
- [x] Ensure that the generated openapi definition is in line with the new specification
- [x] Re-enable automated version bumps for the `openapi-spec-validator` dependency in `inmanta-core/.github/dependabot.yml`
- [x] Verify that the `/docs` renders the api documentation correctly.
