### ISSUE TITLE
Update Agent with deploy endpoint

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#2940]
# Todo

- [ ] Handlers get a `deploy` api that is called even if dependencies have failed. Backward compatibility with the old api, is maintained by calling into execute.
- [ ] The agent is updated to use the new api's
- [ ] The `processing_events` state is no longer reported to the server.
- [ ] reload functionality is ported to the new deploy endpoint, using this event history helper

process_events is no longer supported after this change. 

# Suggestions

```python
def deploy(self, ctx: HandlerContext, resource: Resource, requires: Dict[ResourceIdStr, ResourceState]):
        if all(require.status == ResourceState.deployed for require in requires.values):
            self.execute(ctx, resource, False)
        # some magic to make reload work
```
