### ISSUE TITLE
perform iso5 release

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#3564]
# Things that need to go in after RC1

- all those for ISO4.4.1(https://github.com/inmanta/irt/issues/1002)
- https://github.com/inmanta/inmanta-core/pull/3792 -> merged
- https://github.com/inmanta/pytest-inmanta-lsm/pull/184 -> ongoing
- https://github.com/inmanta/pytest-inmanta-lsm/pull/182 -> merged
- https://github.com/inmanta/inmanta-core/issues/3797 / https://github.com/inmanta/inmanta-core/pull/3799 -> ongoing

# TODO
- [x] (#947) Perform a patch release for all modules with unreleased dependency updates.
- [x] Ensure that the compiler version (`src/inmanta/__init.py__`) has been bumped since the last release or no improvements
    have been made to the compiler since.
- [x] A database dump of the current version is included in the `tests/db/dumps` directory, along with a test that verifies
    the migration (on inmanta-core and inmanta-lsm).
- [x] [run RC release job](https://jenkins.inmanta.com/job/releases/job/inmanta-service-orchestrator-release/)
- [x] [build npm packages](https://jenkins.inmanta.com/job/releases/job/npm/) (build only!)
    - [x] dashboard
    - [x] web-console
- [x] [run next build](https://jenkins.inmanta.com/job/releases/job/inmanta-service-orchestrator-build/)
- [x] [run next build documentation](https://jenkins.inmanta.com/job/docs/job/iso-docs-build/)
- Run the RC tests
    - [x] Quickstart-lsm (manual: See ISO product documentation under Module guides -> LSM module -> LSM quickstart)
    - [x] Performance test ([automated](https://jenkins.inmanta.com/job/integration-tests/job/performancetest/))
    - [x] Compiler scaling ([automated](https://jenkins.inmanta.com/job/integration-tests/job/compilerscaling/))
    - [x] Modulesets ([automated](https://jenkins.inmanta.com/job/modules/job/specific_module_set/job/master/))
    - [x] UC1 (ask Bart)
    - [x] UC2 (ask Wouter)
    - [x] CBCI (ask Bart)
    - [x] Verify that the next release of the documentation looks ok (See: https://docs.inmanta.com/inmanta-service-orchestrator-next/<major-release-nr>/)
- [x] [run project invariant check](https://jenkins.inmanta.com/job/product/job/check-all-project-invariants/job/master/) to guard against patching mistakes
- [x] [run stable release job](https://jenkins.inmanta.com/job/releases/job/inmanta-service-orchestrator-release/)
- [x] [build npm packages](https://jenkins.inmanta.com/job/releases/job/npm/) (build only!), might have been built and published already if there are aligned branches.
    - [x] dashboard
    - [x] web-console
- [x] [run stable build](https://jenkins.inmanta.com/job/releases/job/inmanta-service-orchestrator-build/)
- [x] [run stable build documentation](https://jenkins.inmanta.com/job/docs/job/iso-docs-build/)
- [x] [release module set](https://jenkins.inmanta.com/job/releases/job/iso-modules/)
- [x] inform marketing people

# After major release
- [x] Make sure https://docs.inmanta.com/inmanta-service-orchestrator/ redirects to the newly released version.
- [x] Mention the new major release on the website https://inmanta.com/resources/docs/ (Ask Wouter or Bart)
- [x] Set up dependabot for the new branches: on master, update the config to enable dependabot updates for master and the newly
    created named iso branch. Disable it for the previously listed iso branch because that one should only receive security
    updates (inmanta/irt#512). Merge the config change using the merge tool, which acts as a guard against accidental branch
    divergence.
- [x] Update the following pipelines to run against the newly released version:
    - [x] `pytest-inmanta-lsm`
    - [x] `vscode-inmanta`
    - [x] `inmanta-sphinx`
    - [x] `docker-pytest`
- [x] Update the traffic light config in the `infra` model to include the newly created named iso branches for all relevant
    pipelines. Disable traffic light reporting for iso versions support was dropped for, if any.
- [x] Update the `iso` and `infra` modules to include the new version so orchestrator instances can be launched from the
    management orchestrator.

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3564?planning-poker) with ZenHub @sanderr @arnaudsjs @FloLey @bartv
