### ISSUE TITLE
modules update command does not install module dependencies

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#3623]
# Description
It looks like `inmanta modules update` loads the AST and installs required modules (`Project.load_module_recursive(install=True)`), but does not install Python dependencies of v1 modules (`Project.install_modules()`).

I believe this means a breaking bug in the server. Suppose the server gets a compile request with `force_update=True` for a model with a new Python dependency in one of its v1 modules (or a model that has never been compiled before). In this case, the server only calls `inmanta modules update`, not `inmanta project install`. If this does not install Python dependencies, compilation of the model will fail.

# Steps to reproduce
Create a simple project with `import ip` as its `main.cf`. Run `inmanta modules update` followed by `inmanta compile`:
```
(temp-update) sander@arthur:~/documents/projects/inmanta/inmanta-model-test$ pip --quiet install -e ../inmanta-core/ 
(temp-update) sander@arthur:~/documents/projects/inmanta/inmanta-model-test$ inmanta modules update
(temp-update) sander@arthur:~/documents/projects/inmanta/inmanta-model-test$ inmanta compile
Unable to load all plug-ins for module ip:
	ModuleNotFoundError while loading plugin module inmanta_plugins.ip: No module named 'netaddr' (/home/sander/documents/projects/inmanta/inmanta-model-test/libs/ip/plugins/__init__.py:18)
```

Compare this with the usage of `inmanta project install`:
```
(temp-install) sander@arthur:~/documents/projects/inmanta/inmanta-model-test$ pip --quiet install -e ../inmanta-core/ 
(temp-install) sander@arthur:~/documents/projects/inmanta/inmanta-model-test$ inmanta project install
(temp-install) sander@arthur:~/documents/projects/inmanta/inmanta-model-test$ inmanta compile
```

# Tasks
- [x] implement the intended behavior
- [x] Alias `inmanta project update` to `inmanta modules update`
- [x] Document semantics of the `inmanta project update` command: it does a full project install, updating all modules and their dependencies to the latest compatible versions.
- [ ] Write a test for a server recompile request with `force_update=True` where a module has gotten a new dependency. Assert that the dependency gets installed in the server's venv.
- [x] Patch compiler service behavior if required

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3623?planning-poker) with ZenHub @sanderr @arnaudsjs @FloLey @bartv
