### ISSUE TITLE
Support Unknowns in Current state compare

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#3919]
For the current state compare api we don't have any test involving resource with Unknowns or any support in the API to indicate unknows.

The [underlying dryrun mechanism](https://github.com/inmanta/inmanta-core/blob/master/src/inmanta/server/services/dryrunservice.py#L92) does handle unknows, but not in a very good way: they are marked as no change, not as unknown.

# Tasks

- [ ] Extend the testcases with Unknows (i.e. Undefined and Skipped_for_undefined resources)
- [ ] Extend the API to indicate which resources are Unknown (preferably in-line with the solution take for agent that are unavailable)
- [ ] Ensure the reported totals are correct when combining agent-down with unknows. 
- [ ] Set the status of the resource to `unknown` or `skipped for unknown` in the "payload" -> make inline with the status in the resource manager.
- [ ] Report the state of status in the diff status in the v2 method
- [ ] 'Unknown*' takes precedence over agent down

Question: do we change the mechanism from https://github.com/inmanta/inmanta-core/pull/3936 to also store the agent down in the payload? cfr https://inmanta.slack.com/archives/CKRF0C8R3/p1646220073677819

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3919?planning-poker) with ZenHub @andraskvr @bartv @Stijnkool
