### ISSUE TITLE
Introduce join table between ResourceAction and a Resource

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#4401]
This is a follow up ticket of #4399 that introduces a join table between the ResourceAction table and the Resource table to allow the potential to query ResourceActions faster.

**Tasks:**

- [x] Introduce a join table between the ResourceAction and the Resource table (Keep the `resource_version_ids` column in the ResourceAction table).
- [x] Implement logic to populate the join table for all existing ResourceActions and add a database migration test.
- [x] Ensure that all write operations to the ResourceAction table also update the join table.
- [x] Verify that all methods that write to this table live in the `ResourceAction` class.
