### ISSUE TITLE
Make queries for ResourceActions use join table

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#4402]
This is a follow up ticket of #4399 and #4401. The goal is to start using the join tables in introduced in #4401.

**Tasks:**

- [x] Update each query for a ResourceAction, as such that it no longer relies on the `resource_version_ids` column of the ResourceAction table, but uses the join table instead.
- [ ] Remove the `resource_version_ids` column from the ResourceAction table. If it is heavily used, keep it in `ResourceAction` as a property that reads from the join table. Make sure to use SQL for the critical path rather than Python.
- [x] test on large dataset
- [x] fix locking during delete
