### ISSUE TITLE
Add support to write collect metrics to the database

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#5124]
This ticket adds the main building blocks of the metrics collection framework and adds support to write metrics to the database.

**Tasks:**

- [x] Add the `EnvironmentMetricsService` slice
- [x] Add support to register MetricsCollectors (`register_metric_collector()` method).
- [x] Add support to write collected metrics to the database (`flush_metrics()` method).
       -> Ensure that counter and non-counter metrics are supported
- [x] Add a timer trigger that invokes the `flush_metrics()` method every minute.
- [x] Log a warning when the executing of the `flush_metrics` method takes longer than 1 minute.
