### ISSUE TITLE
Improve paging and filtering performance of nested queries

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#5222]
# Description

This ticket is known to apply to the ResourceView query (see #5212). It may apply to others as well. Depending on the scope, the fix may be tailored to this specific query or it may have to be a generic query builder improvement. The rest of this ticket description will describe the issue for this query specifically. The first task is then to investigate whether other queries suffer from the same or a similar issue.

In short, the issue is that we do paging with the equivalent of an `OFFSET`. We don't use it directly, but because the filtering (e.g. for the paging) is only applied on the outer layer of the query, we do fetch a bunch of records that we drop for the final result.

# Tasks
- [ ] Investigate whether other queries suffer from the same issue
- [ ] Make the inner query filtering-aware, either generically if it affects other queries, or specifically for this query if it's a unique issue.
- [ ] If feasible, add some kind of test that could catch a big performance regression. A seemingly minor or semantically identical change could have huge performance consequences, so it would be nice if we had a test that just verified the order of magnitude on this query.

# In detail

The query is nested in the sense that it uses a `WITH` clause to declare a subquery. Concretely, it uses a recursive subquery that adds a single resource in each iteration. This recursive query is not aware of the paging, therefore it starts with the very first (according to `ORDER BY`) resource. The paging that is then applied on the outer query drops all irrelevant leading rows. The resulting query generated by the query builder looks roughly as follows:
```
WITH RECURSIVE cte AS (
    ( {subquery_latest_version_for_single_resource(higher_than=None)} )
    UNION ALL
    SELECT next_r.*
    FROM cte curr_r
    CROSS JOIN LATERAL (
        {subquery_latest_version_for_single_resource(higher_than="curr_r.resource_id")}
    ) next_r
)
SELECT *
FROM cte r
WHERE r.resource_id BETWEEN lower AND upper;
```

Simply making the inner query aware of the paging by replacing the `None` on line 2 with `lower`, greatly increases paging performance. The same applies for any custom filtering: filtering at the source prevents us fetching rows we will drop anyway.

While this is a simple change to the query, it is not necessarily simple to apply it through the query builder. The purpose of this ticket is to figure out a way to do so.

## PoC
The management orchestrator has a relatively large data set (+- 3000 resources for 100 versions at the time of writing). As a test, I decided to try a slightly simplified version of the ResourceView query, simulating paging for a resource that appears as 2001th in the ordering (if you try this out some time from now you'd best fetch a new resource id to use as lower boundary, something like `SELECT resource_id FROM resource GROUP BY resource_id OFFSET 2000 LIMIT 1;` should do it). This is the naive query, as we currently implement the paging:
```
DEALLOCATE stmt;     
PREPARE stmt (uuid, varchar(255), integer) AS

WITH RECURSIVE cte AS (
    (
        SELECT r.*
        FROM resource r
        JOIN configurationmodel cm ON r.model = cm.version AND r.environment = cm.environment
        WHERE r.environment = $1 AND cm.released = TRUE
        ORDER BY resource_id, model DESC
        LIMIT 1
    )
    UNION ALL
        SELECT r.*
        FROM cte c
        CROSS JOIN LATERAL (
            SELECT r.*
            FROM resource r JOIN configurationmodel cm ON r.model = cm.version AND r.environment = cm.environment
            WHERE r.environment = $1 AND cm.released = TRUE  AND r.resource_id > c.resource_id
            ORDER BY r.resource_id, r.model DESC
            LIMIT 1
        ) r
)
SELECT * FROM cte
WHERE cte.resource_id > $2
LIMIT $3
;

-- page 100 resource starting with the 2001th
EXPLAIN (ANALYZE, BUFFERS) EXECUTE stmt('f81be80b-8582-499f-b002-7cdd2f2df98a', 'std::Package[ci-pytest-inmanta-lsm-iso7-dev.inmanta.com,name=mailx]', 100);
```

Simply moving the where clause for the filtering into the recursive initializer reduces the execution time from 130ms to 6ms:

```
...
        WHERE r.environment = $1 AND cm.released = TRUE AND r.resource_id > $2
...
    UNION ALL
...
SELECT * FROM cte
LIMIT $3
...
```

**Comment by sanderr** [comment]
Discussed with @wouterdb at 2022-04-11:
- check if other queries suffer from it. If not, just fix this one (unless a straightforward solution pops up but I don't expect so)

**Comment by sanderr** [comment]
Tentative conclusions:
- this is the only query that is impacted by this problem
- what's described above is only part of the problem. There are two pieces missing, one small, one large:
  - limit has to be applied in the inner query as well by keeping track of the current recursive index and filtering `<= limit` on that.
  - the endpoint does a second query to gather metadata, including the total number of records. This counting intrincically requires exhausting the recursive query, so optimizing the query mentioned above will only affect 50% of the problem.

I will make an effort to implement the changes oultined in the description, as well as the limit optimization described above, because at this point it will be an easy 50% win. For the proper resolution, two options can be considered:
1. cache the count in Python. Invalidate it when a new version is released (not exported) or when a cleanup happens.
2. 2 part solution: optimize the common case (don't care about orphaned, doesn't require recursive query), and use a materialized view for the non-common case.

**Comment by sanderr** [comment]
> I will make an effort to implement the changes oultined in the description, as well as the limit optimization described above

Tried in #6566 (last commit is entirely different approach than the rest) but it turned out that ordering also greatly complicates things, because it can not be moved inside the recursive query (that would break the recursion) and keeping it on the outside means the filters can not be moved inside the recursive query. It became clear that this is no longer an easy win, so I broke off the attempt.

**Comment by sanderr** [comment]
Not perfect yet but greatly improved in #7427
