### ISSUE TITLE
Move the filter framework from the lsm extension here

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#7747]
inmanta_lsm has a more elegant way of expressing filters, that is incompatible with DataView

This prevent further cleanup in the exentsion

# todo
- [ ] migrate the newer filter framework to core,
- [ ] make the old one a layer on top of the new one
- [ ] port dataview to new framework on core
- move code on the extension onto the new dataview (ticketize)
