### ISSUE TITLE
fix resource scheduler FIXMEs

### ISSUE THREAD

**Issue by Hugo-Inmanta** [inmanta/inmanta-core#8123]
## scheduler.py

```py
class ResourceScheduler(TaskManager):

    async def _build_resource_mappings_from_db(self, version: int | None = None) -> Mapping[ResourceIdStr, ResourceDetails]:
        # FIXME[8118]: resources have not necessarily been released
```

- [x] https://github.com/inmanta/inmanta-core/issues/8118

```py
    ...
    async def read_version(
        self,
    ) -> None:
        # FIXME[8119]: version does not necessarily correspond to resources' version
        #       + last_version is reserved, not necessarily released
        #       -> call ConfigurationModel.get_version_nr_latest_version() instead?
```

- [x] https://github.com/inmanta/inmanta-core/issues/8119

_______

## work.py

```py

class AgentQueues(Mapping[tasks.Task, PrioritizedTask[tasks.Task]]):
    # FIXME[#8019]: relies on undocumented asyncio.PriorityQueue._queue field and the fact that it's a heapq,
    #               can we do something about that?
```

- [ ] https://github.com/inmanta/inmanta-core/issues/8019
```py
    ...
    def sorted(self, agent: str) -> list[PrioritizedTask[tasks.Task]]:
        # FIXME: remove this method: it's only a PoC to hightlight how to achieve a sorted view

```

```py
    ...
    def deploy_with_context(...)
        def extend_blocked_on(...)
            # FIXME[#8015]: default priority
```
- [ ] https://github.com/inmanta/inmanta-core/issues/8015

```py
        ...
        # FIXME[#8015]: priority
```

- [ ] https://github.com/inmanta/inmanta-core/issues/8015

```py
    ...
    def finished_deploy(self, resource: ResourceIdStr) -> None:
        # FIXME[#8012]: event propagation + test
```
- [x] https://github.com/inmanta/inmanta-core/issues/8012

________

## state.py

```py
...

class ResourceState:
    # FIXME: review / finalize resource state. Based on draft design in
    # https://docs.google.com/presentation/d/1F3bFNy2BZtzZgAxQ3Vbvdw7BWI9dq0ty5c3EoLAtUUY/edit#slide=id.g292b508a90d_0_5
```
- [x] https://github.com/inmanta/inmanta-core/issues/8204

________

## tasks.py

```py
    ...


class Deploy(Task):
    async def execute(self, task_manager: "scheduler.TaskManager", agent: str) -> None:
        # FIXME: code loading interface is not nice like this,
        #   - we may want to track modules per agent, instead of types
        #   - we may also want to track the module version vs the model version
        #       as it avoid the problem of fast chanfing model versions
```
- [ ] https://github.com/inmanta/inmanta-core/issues/8205

```py
    ...

        # FIXME: reason argument is not used
```
- [x] https://github.com/inmanta/inmanta-core/issues/8207
```py
    ...


class DryRun(Task):
    async def execute(self, task_manager: "scheduler.TaskManager", agent: str) -> None:
        # FIXME: seems weird to conclude undeployable state from generic Exception on either of two method calls
```
- [ ] https://github.com/inmanta/inmanta-core/issues/8206
```py
    ...

class RefreshFact(Task):
    async def execute(self, task_manager: "scheduler.TaskManager", agent: str) -> None:
        # FIXME, should not need resource details, only id, see related FIXME on executor side

```
- [ ] https://github.com/inmanta/inmanta-core/issues/8208

**Comment by sanderr** [comment]
Scheduling with goal:
- check which are already dedicated tickets or already fixed
- create dedicated tickets for the rest
