### ISSUE TITLE
Read in logging config options.

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#8217]
This ticket should make sure that the different Inmanta components use the correct Inmanta config file.

Design document: https://github.com/inmanta/designs/blob/master/configurable-logging.md

**Tasks:**

- [ ] Add the `logging.server`, `logging.scheduler`,`logging.compiler_service`,`logging.agent` and `logging.cli` config options.
- [ ] Use the following precedence rules when considering logging config files

    * If the `--logging-config` CLI option is set (inmanta or inmanta-cli command), use it.
    * If the logging config environment variable is set for the component being executed, use it.
    * If the global server config contains a logging config for the Inmanta component being executed, use it.
    * Otherwise, fall back to the old behavior, i.e. all old logging-related config options (CLI and server configuration options) will be taken into account.

- [ ] Make sure to always take into account the `-v` option as mentioned in the design document.
- [ ] Log a deprecation message if the new logging config is used in combination with an old logging-related CLI option, saying that the old options will be ignored.

**Comment by arnaudsjs** [comment]
Closing this ticket because it's already implemented.
